name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Generate
        env:
          NUXT_APP_BASE_URL: /catnation/   # ensure baseURL at build time
        run: npx nuxi generate
      # SPA fallback so client-side routes work on refresh:
      - name: SPA Fallback
        run: cp .output/public/200.html .output/public/404.html || true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
